In [ ]:
import pandas as pd
df = pd.read_csv("../stringent_filterTRUE.tsv", sep="\t")
df
binbed = pd.read_csv("../bin_200kb_all.bed", sep="\t", names=["chrom", "start", "end", "bin_id"])
binbed["chrom"] = pd.Categorical(binbed["chrom"], categories=["chr{}".format(e) for e in range(1,23)] + ["chrX", "chrY"], ordered=True)
binbed = binbed.sort_values(by=["chrom", "start", "end"]).reset_index(drop=True)
binbed = binbed.loc[~binbed["chrom"].isin(["chrY"])]
binbed

      chrom      start        end               bin_id
0      chr1          0     200000          bin_200kb_1
1      chr1     200000     400000          bin_200kb_2
2      chr1     400000     600000          bin_200kb_3
3      chr1     600000     800000          bin_200kb_4
4      chr1     800000    1000000          bin_200kb_5
...     ...        ...        ...                  ...
15161  chrX  155200000  155400000      bin_200kb_15140
15162  chrX  155400000  155600000      bin_200kb_15141
15163  chrX  155600000  155800000      bin_200kb_15142
15164  chrX  155800000  156000000      bin_200kb_15143
15165  chrX  156000000  156200000  bin_200kb_15143_end

[15166 rows x 4 columns]

In [ ]:
import pandas as pd
df = pd.read_csv("../stringent_filterTRUE.tsv", sep="\t")
df
binbed = pd.read_csv("../bin_200kb_all.bed", sep="\t", names=["chrom", "start", "end", "bin_id"])
binbed = binbed.loc[~binbed["chrom"].isin(["chrY"])]
binbed
l = list()

def process_row(r):
    # print(r["cell"])
    tmp_r = binbed.loc[(binbed["chrom"] == r["chrom"]) & (binbed["start"] >= r["start"]) & (binbed["end"] <= r["end"])]
    tmp_r["cell"] = r["cell"]
    tmp_r["sv_call_name"] = r["sv_call_name"]
    tmp_r["af"] = r["af"]
    tmp_r["llr_to_ref"] = r["llr_to_ref"]
    # print(tmp_r)
    l.append(tmp_r)

def process_sv(tmp_df):
    tmp_df.apply(lambda r: process_row(r), axis=1)
    # print(tmp_df)
    # exit()


df.groupby("cell").apply(lambda r: process_sv(r))
# print(l)
processed_df = pd.concat(l)
processed_df

,chrom,start,end,bin_id,cell,sv_call_name,af,llr_to_ref
83,chr1,16600000,16800000,bin_200kb_84,BM510x3PE20401,idup_h1,0.39,inf
716,chr1,143200000,143400000,bin_200kb_717,BM510x3PE20401,complex,0.62,inf
733,chr1,146600000,146800000,bin_200kb_734,BM510x3PE20401,inv_hom,0.52,55.394043
734,chr1,146800000,147000000,bin_200kb_735,BM510x3PE20401,inv_hom,0.52,55.394043
735,chr1,147000000,147200000,bin_200kb_736,BM510x3PE20401,inv_hom,0.52,55.394043
...,...,...,...,...,...,...,...,...
7018,chr8,11600000,11800000,bin_200kb_7012,RPE1WTPE20495,inv_h1,0.62,inf
7019,chr8,11800000,12000000,bin_200kb_7013,RPE1WTPE20495,inv_h1,0.62,inf
7796,chr9,22000000,22200000,bin_200kb_7789,RPE1WTPE20495,del_h1,0.98,inf
7797,chr9,22200000,22400000,bin_200kb_7790,RPE1WTPE20495,del_h1,0.98,inf
7890,chr9,40800000,41000000,bin_200kb_7883,RPE1WTPE20495,dup_hom,0.14,inf